# Generated by Django 4.0.5 on 2022-07-02 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_contactform'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactform',
            old_name='custumer_email',
            new_name='customer_email',
        ),
        migrations.RenameField(
            model_name='contactform',
            old_name='custumer_name',
            new_name='customer_name',
        ),
    ]
