# Generated by Django 4.0.5 on 2022-07-02 00:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_rename_custumer_email_contactform_customer_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactform',
            old_name='customer_email',
            new_name='costumer_email',
        ),
        migrations.RenameField(
            model_name='contactform',
            old_name='customer_name',
            new_name='costumer_name',
        ),
    ]
